### ISSUE TITLE
Closing active tab (or group containing active tab) causes the extension window to disappear

### ISSUE THREAD

**Issue by amoawad** [islamElbanna/Tabs-Manager#12]

**Comment by islamElbanna** [comment]
I think its a limitation from chrome: https://developer.chrome.com/extensions/faq

> Can extensions keep popups open after the user clicks away from them?
> No, popups automatically close when the user focuses on some portion of the browser outside of the popup. There is no way to keep the popup open after the user has clicked away.

When close the active tab the focus changed to other tab and that's why the popup closed by chrome
