### ISSUE TITLE
When leaving a tab to another tab, original tab scrolls up to the start of the page

### ISSUE THREAD

**Issue by ahmed-mahran** [islamElbanna/Tabs-Manager#19]
When leaving a tab to another tab, original tab scrolls up to the start of the page. This is sometimes very frustrating when you get back to the original tab and scroll down again to where you left.

**Comment by islamElbanna** [comment]
Its a known issue in html2canvas lib, Fixed by remove the scroll to top from lib
http://stackoverflow.com/questions/18935518/on-render-in-html2canvas-the-page-is-scrolled-to-the-top
