### ISSUE TITLE
Show all grouped tabs first, then ungrouped

### ISSUE THREAD

**Issue by amoawad** [islamElbanna/Tabs-Manager#2]
In my case, there were 4 groups:
- docs.google.com
- github.com
- Other
- www.google.com.eg

Under each group, there were many tabs, the Other (ungrouped), should have been the last group.

**Comment by islamElbanna** [comment]
Add more meaning full name for the ungrouped group
Change the (ungrouped)  group from `others` to `Domains with single tab`
