### ISSUE TITLE
Long pages load very slow

### ISSUE THREAD

**Issue by mahmoudhanafy** [islamElbanna/Tabs-Manager#23]
I've been using the extension for a long time. Currently I'm having a problem to scroll down long pages for example like this [page](https://hbase.apache.org/book.html). I removed the extension and I found that the pages load very fast.

**Comment by islamElbanna** [comment]
It's an issue of html2canvas Lib ... raised and issue for it https://github.com/niklasvh/html2canvas/issues/835

Currently i have prevent parsing large pages > 10,000 dom element

**Comment by mahmoudhanafy** [comment]
Thanks a lot.
